### ISSUE TITLE
MIT-licensed files seem to include GPL-licensed code

### ISSUE THREAD

**Issue by Acharvak** [probonopd/AppImageKit#100]
It seems that [runtime.c](https://github.com/probonopd/AppImageKit/blob/11c9465c23585da122ae3e6a6a38ba56b55f0bec/runtime.c) includes code "adapted from" glib, which is under the GPL (or LGPL, but in this case it doesn't matter, because the code is not just linked statically, but copied).

Please clarify: under what license must the resulting AppImages be distributed? Is it necessary to accompany binary AppImages with the source code for AppImageKit or the application itself?

**Comment by probonopd** [comment]
As stated in [COPYING](https://github.com/probonopd/AppImageKit/blob/master/COPYING), our objective for the original source code in this repository is to have as few restrictions as possible; this is why we chose the MIT license. However, some dependencies used are under other licenses; ideally we would swap thouse out for BSD counterparts as discussed in #69. Since `runtime.c` is not linked against the payload contained inside the AppImage, I assume that it is no problem to distribute proprietary, closed-source software inside an AppImage. Let's continue this discussion in #69.
