### ISSUE TITLE
Support for webapplications

### ISSUE THREAD

**Issue by brauliobo** [probonopd/AppImageKit#134]
Hi, first time here. Do you have ideas how to use appimage with ruby on rails and postgresql dbs?

**Comment by RazZziel** [comment]
That's probably not the use case for AppImage. This is more geared torwards desktop applications; if you want web applications with databases, your solution is probably something more like Docker or LXC.

In order to use an AppImage, you'd need to setup ruby and postgresql inside the AppImage, and a script to set up everything so that that database is initialized in a writable directory (AppImages are read-only), etc.

**Comment by brauliobo** [comment]
hmm, that would be very interesting for open source web applications like github.com/noosfero/noosfero and https://github.com/discourse/discourse

**Comment by probonopd** [comment]
I agree with RazZziel, wouldn't that be great cases for Docker or LXC rather than AppImage?
