### ISSUE TITLE
Website has malicious spamware redirect on Android?

### ISSUE THREAD

**Issue by cathalgarvey** [probonopd/AppImageKit#136]
When I visit [your website](http://appimage.org) from an Android browser without uBlock or other spamware blockers enabled, I immediately get a popup saying "you have messages on facebook" and get redirected, no matter which option I select, to Facebook. Thankfully I don't use Facebook, ever, so I just hit a Facebook login page.

I've tried digging into the source and scripts and can't find the spamware in question; possibly the malicious script in question is only shipped to user-agents matching Android, and I haven't tried spoofing user-agent with `curl` yet.

Also possible is that I have some sort of malware on my own phone doing this, but frankly I doubt it, and the issue only affects your site.

**Comment by chrisnharvey** [comment]
I too am getting this issue on my Android phone.

**Comment by RazZziel** [comment]
Hmmmm I'm not getting this issue on my phone (Chrome @ Android 5.0), and I don't have any ad blocker. Does it happen in the landing page? Right after loading?

**Comment by probonopd** [comment]
Could http://sharebutton.org be the culprit?

**Comment by chrisnharvey** [comment]
@probonopd Could well be, that was the only 'suspicious' external script that I could see in the source.

**Comment by probonopd** [comment]
Removing it for now; please verify if this solves the issue.

**Comment by chrisnharvey** [comment]
@probonopd That solved the issue for me!

**Comment by probonopd** [comment]
Damn share buttons. Can someone recommend a better, trusted social sharing widget?

**Comment by cathalgarvey** [comment]
Problem solved, it was the share button. I couldn't find anything in their source, but must be user-agent distinguished at server-layer rather than script, or something.

Thanks!

**Comment by chrisnharvey** [comment]
Hmm, I've always used AddThis for share buttons, but haven't used it in a while, so I don't know what its like these days.

**Comment by shoogle** [comment]
Instead of having a "share" button, why not create a Facebook and/or Google+ page for AppImage? Many open source projects have social media pages these days - it helps connect with users rather than just developers. You don't need to put much on it - maybe just release a status each time an AppImage gets released for a new program, or give admin rights to a few trusted people to help manage it.

**Comment by probonopd** [comment]
Maybe it's just me but I always cringe when I see companies or projects announce stuff on 3rd party websites rather than their own site. (The most extreme case is some companies doing customer support on Twitter...)
That being said, I do post stuff to https://plus.google.com/explore/AppImage from time to time.
