### ISSUE TITLE
How do I create AppImages for different architectures?

### ISSUE THREAD

**Issue by jviotti** [probonopd/AppImageKit#139]
We're currently generating x86_64 images over here at https://github.com/resin-io/etcher, but are hoping to generate x86 images as well.

By skimming through the documentation, AppImageKit injects a run-time that is platform dependent, a task performed by AppImageAssistant I guess.

Given I already have a compiled x86 application, is there an easy way I can generate an AppImage from a x86_64 machine?

**Comment by jviotti** [comment]
As far as I see, adding an x86 `AppRun` to the package and then creating the image with an x86_64 AppImageAssistant *should* work. I can't find a readily published x86 version of `AppRun` though.

**Comment by probonopd** [comment]
We don't offer precompiled versions for other architectures yet, but you should be able to compile AppImageKit for other architectures without much trouble.

**Comment by RazZziel** [comment]
> As far as I see, adding an x86 `AppRun` to the package and then creating the image with an x86_64 AppImageAssistant *should* work.

Nope @jviotti, because there's also the `runtime` binary that gets injected in the header of the AppImage, which right now will be x86_64 if you're using a x86_64 AppImageAssistant.

That was fixed in https://github.com/probonopd/AppImageKit/pull/130 (merge pending), which lets use a single AppImageAssistant to create AppImages for multiple architectures (for now x86 and x86_64, ARM in progress in https://github.com/probonopd/AppImageKit/issues/111), passing the `--arch` argument.

> I can't find a readily published x86 version of `AppRun` though. 

That was also fixed in https://github.com/probonopd/AppImageKit/pull/120 (merge pending). Meanwhile, you can use docker [like we do](https://github.com/probonopd/AppImageKit/blob/feature/build_3rd_party_dependencies/.travis.yml) in order to build AppImageKit for x86 and generate your packages, or use [MuseScore](https://github.com/musescore/MuseScore/)'s approach to generating [x86](https://github.com/musescore/MuseScore/blob/master/.travis.yml#L82), [x86_64](https://github.com/musescore/MuseScore/blob/master/.travis.yml#L69) and [ARMhf](https://github.com/musescore/MuseScore/blob/master/.travis.yml#L97) AppImages.

**Comment by probonopd** [comment]
So, do people think #120 and #130 are ready for primetime?

**Comment by jviotti** [comment]
Happy to give #130 a spin for Etcher, and report back the results.

**Comment by probonopd** [comment]
For now you can download AppImageKit and compile it on your target architecture, this will give you runtime, AppRun, and everything else you need for your target architecture.

Also, I am collecting votes on whether #120 and #130 are ready for merging.

**Comment by notklaatu** [comment]
So far, I'm just cross-compiling. It seems to work quite well, but admittedly I am only compiling two things (AppRun itself and wxWidgets, sometimes) and the rest is Python. I'd be interested in trying 130 at least (120 was tl;dr)

**Comment by probonopd** [comment]
I assume this question is answered; if not, please reopen.

**Comment by probonopd** [comment]
To everyone reading this, if you are interested in ARM builds, check out Open Build Service which can build AppImages for 32-bit and 64-bit Intel and ARM architectures. Instructions: https://github.com/probonopd/AppImageKit/wiki/Using-Open-Build-Service
