### ISSUE TITLE
What is orbital apps

### ISSUE THREAD

**Issue by crayxt** [probonopd/AppImageKit#145]
https://www.orbital-apps.com/

**Comment by crayxt** [comment]
Cannot find source code of tool

https://www.orbital-apps.com/documentation/orb-specification

ORB Specification
Quick overview

* The specification for the ORB format is completely open and publicly available.
* An .orb file is, in reality, and .iso (ISO-9660) file, with contents added, and additional metadata, but still remaining a valid and standard-compliant ISO-9660 file
* All our .orb apps are currently compressed (with squashfs), making them up to 65% smaller.
* ORB Apps can include both an x86 (32 bits) and an x86_64 (64 bits) version inside the same container, making them ideal for roaming to different computers, with different Linux distros.
* All our current portable apps support the Portable Mode, which means if they run on a USB Drive, they will store settings data in that same drive.
* All .orb portable apps work without the ORB Launcher installed (thanks to an embedded launcher) and don’t require any root permissions ( instructions )
* We are working hard to release a tool to package an app and create an .orb file (ORB Creator), stay tuned!

**Comment by lbssousa** [comment]
ORB Specification:
https://www.orbital-apps.com/orb_specification.txt

ORB Launcher source code:
https://www.orbital-apps.com/documentation/source-code

**Comment by probonopd** [comment]
Seems like they were "inspired" by us. Why don't they contribute but try to roll their own? We should invite them here :-)

**Comment by crayxt** [comment]
I couldn't find contacts on that website

**Comment by lbssousa** [comment]
Contact:
https://www.orbital-apps.com/contact

**Comment by crayxt** [comment]
yeah, thank you. I meant, I expected some more details, like a statement saying we are such and such people.

**Comment by probonopd** [comment]
Investigated this a bit:
* It needs a runtime to be installed. Which means that you can't just download and run an ORB unlike an AppImage
* It puts an executable header into an ISO like AppImage
* It uses autorun.inf and autorun.sh files that GNOME executes when mounting the image. That could be done with AppImages too
* Inside the ISO, there is a squashfs filesystem. This has a better compression that zisofs which AppImage uses, but I am not sure a) why they put one image into another image and b) what this does to performance. I suspect they do it because an ISO has free space in the beginning of a file where an executable can be embedded; however since ORB requires a runtime anyway it is unclear to me why they need this.

**Comment by kskarthik** [comment]
Appimage is mature than orb & we are getting adopted by upstream app dev's in recent days. There is no point in making another format. Infact, both technologies behave the same at the core.
