### ISSUE TITLE
Make AppImageKit installable

### ISSUE THREAD

**Issue by opoplawski** [probonopd/AppImageKit#162]
```
/usr/bin/make install
make: *** No rule to make target `install'.  Stop.
```

Should be able to install this into a common location.

**Comment by probonopd** [comment]
As in `sudo install AppImageAssistant AppImageExtract AppRun /usr/local/bin/`?

Well, AppImageAssistant and AppImageExtract are AppImages themselves and as such do not need to be _installed_, although it doesn't hurt to put them e.g., in `/usr/local/bin` (although I tend to keep all my AppImages on a USB drive). AppRun isn't even intended to be run on its own, instead it is a component to be placed inside an AppImage, so putting it into `/usr/local/bin` and hence on the `$PATH` isn't really that useful.

**Comment by opoplawski** [comment]
Say you have a multi-user system and you would like to install a single, common AppImageKit package on that system so developers on that system could build AppImages, what would need to be installed?

**Comment by probonopd** [comment]
`AppRun` and `AppImageAssistant` would be needed but they wouldn't __need__ to be _installed_ since `AppRun` is something that goes _into_ the AppImage being created and `AppImageAssistant` is an AppImage itself, making it _unneccessary_ to install it. I am a huge fan of "eating one's own dogfood" ;-)

Here are some examples of how AppImages can be built:
https://github.com/probonopd/AppImages/tree/master/recipes

That being said, I am not against adding a make target 'install', I simply didn't see much need for it so far.

**Comment by probonopd** [comment]
Feel free to reopen if anyone wants to work on it. Distributing the AppImageKit components as AppImages is sufficient for me.
