### ISSUE TITLE
desktopintegration: Why icon thumbnail created and Icon key changed

### ISSUE THREAD

**Issue by develar** [probonopd/AppImageKit#190]
```
ABS_APPIMAGE=$(readlink -e "$APPIMAGE")
ICONURL="file://$ABS_APPIMAGE"
MD5=$(echo -n $ICONURL | md5sum | cut -c -32)
ICONFILE="$HOME/.cache/thumbnails/normal/$MD5.png"
if [ ! -f "$ICONFILE" ] ; then
  echo "$ICONFILE is missing. Probably not running ${THIS} from within an AppImage."
  echo "Hence falling back to using .DirIcon"
  ICONFILE="$APPDIR/.DirIcon"
fi
```

I don't understand for what this code is needed. Icons correctly installed to `~/.local/share` (i.e. not part of the image), so, Ubuntu correctly displays icons. 

Or is this required for apps without `./usr/share/icons/` (because AppImage currently doesn't create it from .DirIcon automatically)? In this case I suppose it should be fixed and, so, this code can be removed?

electron-builder always creates `./usr/share/icons/` and I removed this code in my version of `desktopintegration`.

**Comment by probonopd** [comment]
When you are running an AppImage, then the runtime ELF code installs the icon into the thumbnailer location outside of the AppImage in `$HOME/.cache/thumbnails/normal/`.

But when you are running the AppRun file without it being inside an AppImage (then it is in fact an [AppDir](http://rox.sourceforge.net/desktop/AppDirs.html) rather than an AppImage), then there is no runtime ELF which could have installed the icon into the thumbnailer location; in this case, we are using the `.DirIcon` inside the AppDir.
