### ISSUE TITLE
AppImageMonitor broken

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#33]
```
# Ubuntu 15.10
me@host:~/AppImageKit$ ./AppImageMonitor
7222 (process ID) old priority 0, new priority 1
Directory /home/me/Applications/ doesn't exist
me@host:~/AppImageKit$ mkdir  /home/me/Applications/
me@host:~/AppImageKit$ ./AppImageMonitor
7237 (process ID) old priority 0, new priority 1
Watching /home/me/Applications/...
The databases in [//home/me/.local/share/applications] could not be updated.
./bin//monitorAppImages.sh: line 141: inotifywait: command not found
```

It should: 
 * Create the needed directories
 * Watch $HOME/Downloads. It could ask whether it should do that.
 * Make AppImages executable after asking
 * Optionally install the .desktop file and icon into the system.  It could ask whether it should do that.
 * Use the same logic and location for the icon as `runtime.c` so that we don't extract the same icon in multiple locations

**Comment by RazZziel** [comment]
(Discussion continued from https://github.com/RazZziel/PortableLinuxGames/issues/1)

>Create the needed directories

Hmmmm, not sure. The script doen't *need* direcctories to operate (besides all the `~/.local` stuff), it adapts to the directories the user wants.

However, provided it's supposed to be a daemon, it's indeed wrong to abort if ~/Applications doesn't exist and no other directory is provided. If the default Applications directory doesn't exist, instead of aborting it should ask the user to select/create a directory, or wait for the default directory to be created.

However², that's something the final version of the script should do; probably a version implemented in PyGtk, with a system tray icon, possibility to show dialogs more polished than the ones zenity can show, etc. Provided the bash version is mostly a prototype, we can for now create `~/Applications`, maybe with a custom directory icon.

>Watch $HOME/Downloads

Will users want that? It'd be cool to make downloaded AppImages executables by default, as that's probably the most difficult step in using AppImages for new users, but maybe we should wait for the user to explicitly move the app to his Applications directory before assuming he wants to have the application in the menu.

>Make AppImages executable after asking

Already done, but we're not asking for now

>Optionally install the .desktop file and icon into the system after asking

Already done, but we're not asking for now

Regarding the `inotifywait` dependency, that's being taking care of (https://clbin.com/EgzMJ, https://github.com/RazZziel/PortableLinuxGames/issues/1#issuecomment-154373760)

**Comment by RazZziel** [comment]
@probonopd any opinion on using the xorriso provided by libburnia or the one provided by GNU? I've implemeted both in the CMakeLists.txt, but the GNU one is commented because *I think* you were using the libburnia one.

**Comment by probonopd** [comment]
@RazZziel I wasn't even aware that there are two different ones. Since the libburnia one works, why not stay with that.

**Comment by RazZziel** [comment]
GNU's one seems to be a static compilation of the latest libburnia's xorriso and most of its dependencies, so the resulting binary is much cleaner

        linux-gate.so.1 (0xb77cf000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0xb776b000)
        libz.so.1 => /usr/lib/libz.so.1 (0xb7753000)
        libc.so.6 => /usr/lib/libc.so.6 (0xb7599000)
        /lib/ld-linux.so.2 (0xb77d0000)

vs libburnia's xorriso

        linux-gate.so.1 (0xb7745000)
        libisoburn.so.1 => /home/raziel/dev/AppImageKit/third-party-dependencies/install/lib/libisoburn.so.1 (0xb763a000)
        libisofs.so.6 => /home/raziel/dev/AppImageKit/third-party-dependencies/install/lib/libisofs.so.6 (0xb75b6000)
        libacl.so.1 => /home/raziel/dev/AppImageKit/third-party-dependencies/install/lib/libacl.so.1 (0xb75ad000)
        libburn.so.4 => /home/raziel/dev/AppImageKit/third-party-dependencies/install/lib/libburn.so.4 (0xb74e8000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0xb7486000)
        libz.so.1 => /usr/lib/libz.so.1 (0xb746e000)
        libc.so.6 => /usr/lib/libc.so.6 (0xb72b4000)
        libattr.so.1 => /home/raziel/dev/AppImageKit/third-party-dependencies/install/lib/libattr.so.1 (0xb72af000)
        /lib/ld-linux.so.2 (0xb7746000)

**Comment by probonopd** [comment]
That clearly speaks in favor of the GNU one then.

**Comment by RazZziel** [comment]
Is `AppImageMonitor` still broken? Or can this task be closed?

**Comment by probonopd** [comment]
There is a much simpler way to extract stuff from AppImages without the need for xorriso using `isoinfo`:
```
APPIMAGE=/home/me/Applications/AppImageMonitor

# Find the desktop file inside the AppImage
DESKTOP=$(isoinfo -J -f -i "${APPIMAGE}" | grep .desktop$ | head -n 1)

# Extract the desktop file
isoinfo -J -i "${APPIMAGE}" "${DESKTOP}"
```

**Comment by probonopd** [comment]
> Is `AppImageMonitor` in the `experimental` branch still broken? Or can this task be closed?
I still cannot compiele `experimental`.

**Comment by RazZziel** [comment]
I've disabled LibcWrapGenerator by default in d36f0767c1a76281a7fad164b408fa3fc8da98d7

**Comment by RazZziel** [comment]
I understand this has long been fixed

**Comment by probonopd** [comment]
Thanks. Cannot test it right now; will reopen if problem persists.

**Comment by probonopd** [comment]
Could [this](https://gist.githubusercontent.com/probonopd/f757f91138fd884737b26879151152c9/raw/44b17a8f6be8b7cfb3bbba07c3c3def21c4e8e35/execute-appimages.sh) remove the need for a daemon altogether? It autmatically sets `chmod a+x` on all binaries that don't have it.
