### ISSUE TITLE
Getting some fuse issues with recent appimagekit in docker

### ISSUE THREAD

**Issue by jcelerier** [probonopd/AppImageKit#388]
I'm getting the following in a centos 6 container: 

    ./appimagetool-x86_64.AppImage ./i-score.AppDir/ ./out/i-score.AppImage 
    fuse: device not found, try 'modprobe fuse' first 

Fuse is of course working in the host, and I can't use modprobe in a container.

**Comment by TheAssassin** [comment]
This is not an issue with AppImages but Docker and FUSE itself and thus off topic. I suggest closing it.

----

The problem you experience is that Docker containers canot use FUSE due to some architectural quirks, unless you allow it to access the host FUSE device. There's many tutorials out there how to work around these kinds of issues (e.g. `--device /dev/fuse:mrw`, and often also `--security-opt apparmor=unconfined` because AppArmor protects FUSE), but I **strongly advise you to not to use any of them**, as they breach several security mechanisms that are there to protect you (and your users).

But here's the good news: Type 2 AppImages don't have a hard dependency on FUSE. As I assume the only AppImage you have to run is appimagetool as you're building another AppImage, here's a FUSEless solution that is way easier to implement: https://github.com/TheAssassin/redeclipse-appimage/blob/master/build-appimage.sh#L157

**Comment by jcelerier** [comment]
okay, I just updated appimage and it used to work hence my issue here. I'll try with your method and reopen another issue if I encounter a problem. Thanks!
