### ISSUE TITLE
AppImageAsistant should not require pygtk2 and libpng12 when run in CLI

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#43]
Currently I have to do `yum install pygtk2 libpng12` to run AppImageAsistant on Fedora 23 even though I do not use the GUI at all. We should only import the GUI stuff if it is needed.

**Comment by RazZziel** [comment]
Is pygtk2 needed also in the experimental branch, when not using the GUI?

**Comment by probonopd** [comment]
Trying that now

**Comment by probonopd** [comment]
Yes it does

**Comment by probonopd** [comment]
i'm still fighting to compile experiemental

**Comment by probonopd** [comment]
I was hoping that the following would do the trick but it does not, am I missing something?

```
if __name__=="__main__":


    for arg in sys.argv:
        if arg in ["--pack", "--package"]:
            if len(sys.argv) < 4:
                usage()
            elif not os.path.exists(sys.argv[2]):
                print sys.argv[2], "doesn't exist"
            elif not os.path.isdir(sys.argv[2]):
                print sys.argv[2], "is not a directory"
            elif os.path.exists(sys.argv[3]):
                print sys.argv[3], "already exists"
            else:
                os.system(os.path.dirname(__file__) + "/package '%s' '%s'" % (sys.argv[2], sys.argv[3]))
            exit(0)
        elif arg in ["--unpack", "--extract"]:
            if len(sys.argv) < 4:
                usage()
            elif not os.path.exists(sys.argv[2]):
                print sys.argv[2], "doesn't exist"
            elif not os.path.isfile(sys.argv[2]):
                print sys.argv[2], "is not a file"
            elif os.path.exists(sys.argv[3]):
                print sys.argv[3], "already exists"
            else:
                origin = "/"
                if len(sys.argv) >= 5:
                    origin = sys.argv[4]
                os.system(os.path.dirname(__file__) + "/extract '%s' '%s' '%s'" % (sys.argv[2], sys.argv[3], origin))
            exit(0)
        elif arg in ["-h", "--help"]:
            usage()
            exit(0)
        else:
            import  gtk, vte
            import dialogs # part of kiwi; bundled with this app
            A = Assistant()
            A.show()
            gtk.gdk.threads_init() # The gtk.gdk.threads_init() function must be called before the gtk.main() function
            gtk.main()
```

**Comment by probonopd** [comment]
https://github.com/probonopd/AppImageKit/commit/6ac57882dbf5daae2a143bf6a974b7facfb3181a closes this. Actually this had been working before it was broken by https://github.com/probonopd/AppImageKit/commit/364f271fb9cebd60a96290daeec7bcc5bd18c2fd

**Comment by RazZziel** [comment]
Ok, the problem was then that 364f271 deliberately removed support for running the application with just three arguments in order to pack, when adding the `--pack` and `--unpack` commands, because it was ambiguous, so you weren't actually running in CLI mode.

If the old behavior needs to be respected, it could've been added **after** the loop that checks for `--pack`, `--unpack`, etc.

Also please bear in mind that
`os.system(os.path.dirname(__file__) + "/package %s %s" % (sys.argv[1], sys.argv[2]))`
instead of
`os.system(os.path.dirname(__file__) + "/package '%s' '%s'" % (sys.argv[1], sys.argv[2]))`
will not respect spaces in filenames

**Comment by probonopd** [comment]
What do you mean by "it was ambiguous, so you weren't actually running in CLI mode"?

Personally, I prefer `cp a b` over `cp --from a --to b` ;-)

**Comment by RazZziel** [comment]
My bad, I should've discussed before happily changing the paradigm of the tool operation:
* `cp a b` works well for `cp`, because that's the only thing `cp` does: copying
* Package format managers like `tar`, `zip`, `7z`, etc, on the other hand, need to specify a command in every invocation, usually _pack_, _unpack_, and _test/list_.

I understand `AppImageAssistant` to be in the same group as `tar`, `zip` and `7z`: one single tool to operate with AppImages. It is true that `AppImageAssistant` is different, in the sense that if run without arguments it will pop up a nice UI to make it compatible with doube-clickers, and specially in the sense that the *pack* command is more important here than the *unpack* command because there's usually no need for the user to unpack an AppImage (compared to the other tools, where packing is just as important as unpacking), but I still think further operations with AppImages should be allowed, even if we let the *pack* command to be the protagonist, allowing it to be run without explicitly declaring `--pack`.

> What do you mean by "it was ambiguous, so you weren't actually running in CLI mode"?
>> it was ambiguous

I meant that no command was specified, although now I think it'd be fine to keep this behavior in this case, being the _pack_ operation more important than any other operation for AppImages

>> so you weren't actually running in CLI mode

My patch implied that you'd run in CLI mode only if an explicit `--pack`, `--unpack` or `--help` command was specified, so if you just specified your three arguments without command, the tool would just ignore the arguments, start the GUI, and fail when trying to load Gtk.
