### ISSUE TITLE
[desktopintegration] Provide a way to "uninstall"

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#67]
Should we provide a way to "uninstall", i.e., remove icons, desktop file, and mimetypes?

**Comment by RazZziel** [comment]
Definitely.

If an AppImage is removed while AppImageMonitor is running, its desktop entries are currencly being removed. The problem is if an AppImage is removed while AppImageMonitor is **not** running: right now I AppImageMonitor has the `--clean` flag in order to remove **all** menu entries, before running without the parameter in order to create them again, but a more correct approach would be to scan `/$HOME/.local/share/applicationsAppImage-*.desktop`, and uninstall the .desktop files whose corresponding AppImage doesn't exist anymore

**Comment by probonopd** [comment]
Note that this is regarding https://github.com/probonopd/AppImageKit/blob/master/desktopintegration but as per your explanation it also applies for AppImageMonitor.

A solution could be:
Rather than having the .desktop file launch the AppImage, have it launch a tiny helper script that checks whether the AppImage is still there, and otherwise uninstalls any associated desktop, icon, mime etc. files that belong to the AppImage, and itself.

**Comment by RazZziel** [comment]
Ah, ok, wasn't aware of _desktopintegration_

> have it launch a tiny helper script that checks whether the AppImage is still there, and otherwise uninstalls any associated desktop, icon, mime etc. files that belong to the AppImage, and itself.

The UX is a bit *dirty*, having to launch a menu entry for an app that's already uninstalled, in order for it to recognize the app is uninstalled and should be removed (imagine you copy 100 apps from a friend, but end up uninstalling them all, selecting all files and deleting them; you still have 100 outdated menu entries that you need to remove manually one by one).

However I really can't come up with anything else that doesn't involve having some kind of AppImageMonitor daemon residing on every AppImage, and launch it as a singleton (only one demon is launched even if there's multiple AppImages installed). Or without involving a daemon, having every AppImage verify and update all other AppImage menu entries in the background upon launch. I didn't really like the idea because it would involve every AppImage needs to cooperate, and AppImages by design can be written in a very heterogeneous way, by different vendors, with or without wrappers, but it could work, although I'd rely more on launching our own integration script in background from the runtime, rather than depending on each vendor tweaking its .desktop to launch the wrapper; that way it'd be much easier to standardize desktop integration without depending on any AppImageMonitor daemon.

**Comment by probonopd** [comment]
_desktopintegration_ is new. It is an experiment to see how far we can get without the need for a daemon. It was inspired by [this](https://blog.michelebosi.com/linux-apps-portability/) blog post.

**Comment by RazZziel** [comment]
Yep, I understand; the daemon I was referring to here was *implicit*, living on each AppImage, so it's transparent for the user: neither the user nor the distro need to have any AppImage integration installed, nor they need to run each AppImage to have its desktop integration updated; all desktop integration starts happening in the background once you have run your first AppImage.

Of course this adds some overhead to each AppImage's content, but it should be okay if it's small enough (i.e. current AppImageMonitor takes 1.2M, which is probably fatter than desirable, but if it shares dependencies (xorriso/fuseiso etc) with the AppImage itself, it could be slimed down, although it would probably grow if we try to incorporate proper UIs. An alternative would be to download the daemon from the internet the first time an AppImage is run and the user agrees to automate desktop integration.

The point of trying to use a daemon, even if it's implicit, would be to enhance UX:
* If the user explicitly moves the AppImage into an "Applications" folder, it should be signal enough that he wants that program to be part of the system, like in OSX. There wouldn't be a need for a "Do you want to add this program to the menu? [yes/no/don't show again]" popup, which I think it's nice (when I click on an AppImage, intuitively I just want the app to start up as soon as possible, not to read through popups, as useful as they may be)
  * If the daemon is implicit, there could be a first, single-time popup that says "This is the first time you run an AppImage. Do you want to add AppImages in the _"Applications" directory automatically to your menu from now on? [yes/no/don't show again]"_, before unpacking or downloading the AppImageMonitor or whatever daemon we come up with.
* Removed AppImages would have its menu integration removed automatically, which I think is important when moving large amounts of AppImages; otherwise I think the user perception would be like _"this fucking AppImage left my menu cluttered as shit"_.
* Some cool stuff is made possible in the background, like right-button menu options, automatic updating, AppImage seeding, etc (which can be seen as pretty intrusive and some people won't like it, so proper UIs and conservative default settings are advised)

**Comment by RazZziel** [comment]
From https://github.com/probonopd/AppImageKit/issues/55#issuecomment-170393763:
> `TryExec=` in the `.desktop` file is supposed to not show the menu entry if the file is no longer there. From time ti time a cleanup script could delete desktop files with TryExec statements with missing associated files.

Didn't know that, should be useful to this task

**Comment by RazZziel** [comment]
https://github.com/probonopd/AppImageKit/commit/bf1ad78aca8073a08b2cdab747362167fc9c59cf implements TryExec and orphaned desktop file removal on AppImageMonitor, but the issue is for _desktopintegration_ so I'm dis-owning it instead of closing it

**Comment by darealshinji** [comment]
Adding a custom action to the desktop file may help:
``` ini
Actions=Uninstall;

[Desktop Action Uninstall]
Exec=uninstall-command
Name=Uninstall this AppImage
```

**Comment by probonopd** [comment]
AppImageMonitor is deprecated and has been replaced by the `appimaged` daemon which takes care of uninstalling automatically if an AppImage is deleted or moved out of the watched directories. Please open a new issue if this does not work for you.
