### ISSUE TITLE
Replace md5

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#69]
Replace `md5.h` and `md5.c` with the algorithm in RFC-1321 Appendix A.3 or, maybe even better, http://openwall.info/wiki/people/solar/software/public-domain-source-code/md5 to prevent from potential license issues.

The same goes for the files in the `linux/` subdirectory.

This should be attempted in a separate feature branch first.

**Comment by RazZziel** [comment]
Regarding md5, there shouldn't be much trouble replacing the GPLd implementation by the reference one, if that one works correctly, although maybe it's easier to use another working implementation with another license, like the one in [musl](http://git.musl-libc.org/cgit/musl/tree/src/crypt/crypt_md5.c) or [wpa_supplicant](https://w1.fi/cgit/hostap/tree/src/crypto/md5.c).

However, taking a step back, md5 is only used in the runtime, for icon extraction. Is this still useful? Is it the replacement for ElfIcon? Shouldn't it be replaced by all the desktop integration we're doing, either in the daemon and in the wrapper? Because it takes up **a lot** of space in the source code (`escape_uri_string`, `to_hex_char`, `uri_from_filename`, `thumbname_from_uri`, `getArg`...), and removing it would probably reduce the runtime size a lot.

Regarding the `linux/` stuff, it's a lot of definitions in the Linux source, I don't think we can replace that, so I guess the runtime **needs** to be GPL, even if the rest of the code isn't. In that case, even if we keep using icons, and thus md5, there wouldn't be a need to replace it.

**Comment by probonopd** [comment]
md5 is needed in order to display the icon. It we could probably move it to AppRun, though.

**Comment by RazZziel** [comment]
It's not that we **need** to move it to avoid the md5, I think it's interesting _per se_, because:
* Removes desktop integration responsability from the runtime
** Right now, desktop integration is duplicated
*** The runtime creates the thumbnail
*** The desktop integration helper (desktopintegration and/or AppImageMonitor) creates the menu entry, register mime types, etc, and it should also handle icons, thumbnails and suchlike
* Reduces runtime size (maybe allowing static compilation of some dependency)
* Reduces startup time for every AppImage (although it's already _good enough_)

**Comment by probonopd** [comment]
Cons: 
 * Lazy people putting together wouldn't have icons working out of the box
 * Everyone needs to use (or reimplement) out AppRun

**Comment by RazZziel** [comment]
Yep, that's why on https://github.com/probonopd/AppImageKit/issues/67#issuecomment-170214328 I mentioned:
> AppImages by design can be written in a very heterogeneous way, by different vendors, with or without wrappers, but it could work, although I'd rely more on launching our own integration script in background from the runtime, rather than depending on each vendor tweaking its .desktop to launch the wrapper; that way it'd be much easier to standardize desktop integration without depending on any AppImageMonitor daemon.

That means, instead of having

    runtime
      |-> AppRun
      |     |-> desktopintegration
      |     |-> app

or

    runtime
      |-> AppRun wrapper
      |     |-> desktopintegration
      |     |-> AppRun
      |     |     |-> app

We'd have

    runtime
      |-> desktopintegration (in background, in a fork()ed process)
      |-> AppRun
      |     |-> app

The only need we'd need to change is:
* **runtime**: `if (fork() == 0) exec("./desktopintegration");`
* **AppImageAssistant**: modify *package* to copy the desktopintegration script in the AppImage being created

**Comment by probonopd** [comment]
Interesting idea. How do we make sure we won't have different, outdated versions of the daemon around?

**Comment by RazZziel** [comment]
We can start without daemon. When I say:
> desktopintegration (in background, in a fork()ed process)

I mean that your current `desktopintegration` script is run in background, but it does its thing and exists, it doesn't keep waiting in the background. It's just started in the background in order not to delay the AppImage startup.

That being said, if we want to move to an implicit daemon, this `desktopintegration` script would install a `AppImageMonitor` program somewhere in the user's data files (i.e. `.local/share/`), and register itself as a service (`.config/autostart` sort of thing). Then, in order to ensure the latest version of AppImageMonitor is installed:
* Each AppImage carries its own version of `AppImageMonitor` inside, and only updates the system's AppImageMonitor if it's newer
* No AppImage carries `AppImageMonitor` inside, but just runs a script that downloads the latest version from the internet

**Comment by probonopd** [comment]
> I mean that your current desktopintegration script is run in background, but it does its thing and exists, it doesn't keep waiting in the background

I see. In theory, something like launching it with "&" and adding a "sleep 10" at the beginning could make sure that the startup of the app is delayed as little as possible by it. But then, have you tested it? It doesn't noticeably delay the app launch on my systems as it is now...

> That being said, if we want to move to an implicit daemon, this desktopintegration script would install a AppImageMonitor program somewhere in the user's data files

I can follow your logic but am a bit undecided whether to like it. Normally I don't like stuff that "trashes" my system - think the stuff in the bottom-right of the Windows taskbar...

**Comment by RazZziel** [comment]
> I see. In theory, something like launching it with "&" and adding a "sleep 10" at the beginning could make sure that the startup of the app is delayed as little as possible by it. 

Sure, but then again, the AppRun is packager code, the runtime is AppImage code, only changing the runtime would standardize desktop integration accross all AppImages, regardless of the packager

> But then, have you tested it? It doesn't noticeably delay the app launch on my systems as it is now...

Indeed it may not noticeable right now, but the `fork()` has mostly no cost and above all it's constant, it doesn't depend on the application (some applications may have many mime types, search plugins, right-click plugins...), or on the features we integrate in _desktopintegration_ (Gnome search integration, index updates, etc). It's mostly a safeguard: if we `fork()`, we can be sure whatever we do in the desktop integration will have no effect on the application startup time, regardless of the complexity of the app.

> I can follow your logic but am a bit undecided whether to like it. Normally I don't like stuff that "trashes" my system - think the stuff in the bottom-right of the Windows taskbar...

Yep, that's a problem, but the features are also interesting. Some users will like it (I like AppImageMonitor being able to integrate all my AppImages, some of them so old they don't even accept the `--icon` argument), but some users will hate it and call it bloatware, that's why I'd at least ask _yes / no / don't show again_.

But anyway, there's always the option of not having a daemon, but having a _desktopintegration_ script that launches in the background, updates desktop integration for all apps (removing old menu entries etc), and quits, not staying in the background.

**Comment by RazZziel** [comment]
Size of the compiled runtime on my machine:
* Before: 30844 bytes
* Now: 23836 bytes

I don't know if that would be enough to link some other library statically. Anyway, the main advantage is to avoid duplicating responsibilities. This branch probably shouldn't be merged until the `fork()` and `exec()` are implemented.

By the way, back in the licensing issue: both fuseiso.c and isofs.c are also GPL and they're linked statically, so AFAIK runtime.c needs to be GPL (or compatible) as well.

**Comment by probonopd** [comment]
Well, simply removing thumbnails altogether is not what I meant by "replace md5 by another md5". But you are right about fuseiso and isofs; are there BSD equivalent implementations that we could use? I don#t have a problem with runtime being GPL at all but I could imagine some companies might consider AppImage more happily if we could put it under a more liberal license.

**Comment by RazZziel** [comment]
> simply removing thumbnails altogether is not what I meant by "replace md5 by another md5"

Of course, but as I said I think removing it it's a better solution altogether (responsibility separation, coherence with desktopintegration, startup time, binary size, etc) so I wanted to try how it would look.

> about fuseiso and isofs; are there BSD equivalent implementations that we could use?

No idea, https://en.wikipedia.org/wiki/Filesystem_in_Userspace says that 
> [FreeBSD 10 added FUSE support in the base system](https://wiki.freebsd.org/WhatsNew/FreeBSD10#FUSE_support_in_the_base_system)
> OpenBSD has [ISC](https://en.wikipedia.org/wiki/ISC_license) licensed [FUSE support](http://undeadly.org/cgi?action=article&sid=20131108082749&mode=expanded&count=2) in base system starting 1

but I don't know if there will be plugins for those fuse ports that can be made compatible with the linux implementation

Anyway meanwhile an alternative is not implemented, the GPL should be respected

**Comment by Acharvak** [comment]
>By the way, back in the licensing issue: both fuseiso.c and isofs.c are also GPL, and they're linked statically, so AFAIK runtime.c needs to be GPL (or compatible) as well.

runtime.c also contains code adapted from glib, as I mentioned in #100.

>Anyway meanwhile an alternative is not implemented, the GPL should be respected

So could somebody please clarify: what license are AppImages to be distributed under? Are they (or any part of them) under the GPL? If so, I believe it's absolutely necessary to mention it in the documentation and say what obligations one has when distributing AppImages.

**Comment by probonopd** [comment]
I would assume that runtime.c is GPL as long as it statically links GPL components. Hence I assume that in order to comply with the GPL you need to put a link to this repository along with the AppImage download link.

Further I assume that the contents contained in an AppImage are not subject to the GPL in any way, as this is [mere aggregation](http://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#MereAggregation).

I am not a lawyer though and I'd appreciate others' thoughts.

**Comment by Acharvak** [comment]
>in order to comply with the GPL you need to put a link to this repository along with the AppImage download link

Might not be enough though. You have to put a link to [the exact version you used](http://www.gnu.org/licenses/gpl-faq.html#SourceInCVS) and if this repository goes down, you are [still responsible](http://www.gnu.org/licenses/gpl-faq.html#SourceAndBinaryOnDifferentSites) for distributing the source code. And if you're distributing it on DVD, you [still have to](http://www.gnu.org/licenses/gpl-faq.html#DistributeWithSourceOnInternet) distribute the source on physical media, if someone requests it in this form. And all of these obligations are not to AppImageKit developers but to the developers of the GPL components.

**Comment by probonopd** [comment]
Idea: Distribute runtime.c or a link to it inside the AppImage. Since the AppImage is just an ISO, I think this is the cleanest solution.

**Comment by probonopd** [comment]
Removed `md5.c`
