### ISSUE TITLE
AppImageAssistant ignores SVGs in favour of PNG icons

### ISSUE THREAD

**Issue by shoogle** [probonopd/AppImageKit#80]
If the desktop file contains the line `Icon=appicon` and there is PNG called "appicon.png" of size 48x48 or larger in "share/icons/hicolor/..." then it is used in preference to an "appicon.svg" in "share/icons/hicolor/...". It is not possible to override this behaviour by putting the SVG in the root of the AppDir, either by naming it "appicon.svg" or ".DirIcon".

My preference would actually be to have the icon search halted altogether if a file called ".DirIcon" was already present, and just to use that instead. This also avoids creating multiple copies of the icon as currently happens.

(Purely as I matter of curiousity, how does the operating system know that it should use .DirIcon as the icon? Is the icon stored in the ISO header or within the compressed part?)

**Comment by probonopd** [comment]
What is inside an AppImage is an AppDir, (loosely) following the [ROX AppDir format](http://rox.sourceforge.net/desktop/AppDirs.html) which specifies the use of a file called `.DirIcon`, among other things. I used this spec as the Basis for AppImages because back in the time I speculated that more file managers than just ROX Filer might use it one day, though that never happened.

Since most `.desktop` files specify an `Icon=appname` entry, AppImageAssistant is written to pick up a suitable icon using that information, and copy it to .DirIcon. I would like to keep it this way because it makes generating an AppImage from a precompiled package much easier (e.g., see `apt-appdir`). Currently it gives preference to 48x48 icons which comes from the GNOME 2 epoch when this size was the preferred icon size. Times have changed and it would probably best to change the algorithm so that:

 * Use, in this order: `AppDir/appname.{svg,png}`; if this fails:
 * Use, in this order: resizable/svg, 512, 256, 128,... icons in `AppDir/usr/share`

Would that fit your needs?

**Comment by shoogle** [comment]
Yes, that would be great, but I was suggesting an extra step:

- If it exists, use AppDir/.DirIcon, otherwise...
- Use, in this order: AppDir/appname.{svg,png}; if this fails:
- Use, in this order: resizable/svg, 512, 256, 128,... icons in AppDir/usr/share

But that's up to you.

**Comment by probonopd** [comment]
Got it, but I find it inconvenient because you have to "clean up" after each AppImageAssistant run which places a new `AppDir/.DirIcon` there... so I'd be in favor of leaving out the extra step.
The relevant code is
https://github.com/probonopd/AppImageKit/blob/34defc0d9fc0b79735b3cdf84cd5c4d3234f9639/AppImageAssistant.AppDir/xdgappdir.py#L43-L48 for determining the order of locations (AppImage root first, AppImage/usr/share/icons second, host system third) and
https://github.com/probonopd/AppImageKit/blob/34defc0d9fc0b79735b3cdf84cd5c4d3234f9639/AppImageAssistant.AppDir/xdgappdir.py#L61-L67 for determining the format and size.

Can you figure it out from here? If not let me know and I'll have a look at it when I find time.

**Comment by probonopd** [comment]
AppImageAssistant hast been replaced by `appimagetool`. Use it instead.
