### ISSUE TITLE
Constant mount point, at least as option.

### ISSUE THREAD

**Issue by bengtmartensson** [probonopd/AppImageKit#83]
Some programs, like IrScrutinizer, needs the path to program components to be constant. The current mount takes place at a random mount point, breaking those programs, see https://github.com/bengtmartensson/harctoolboxbundle/issues/65#issuecomment-183482664.

A mount point could be given as a (optional) argument to the AppImageAssistant, if given, it is used, if not given, the present behavior is used.

**Comment by probonopd** [comment]
I don't like this idea, because it prevents apps from being portable (as in: can move the app around in the filesystem). I have been working with this scheme for 10+ years now and 99% of apps don't have any issue with it. If an app does have issues with it, then it's an indication that the app is saving absolute paths internally which it shouldn't.

Please explain a use case in which this is absolutely needed.

**Comment by bengtmartensson** [comment]
Since I am no longer a stake holder (https://github.com/bengtmartensson/harctoolboxbundle/issues/100), I do not want to hold this issue open. I still find it a very sensible request, and I am not persuaded by your arguments. Letting the user select a file anywhere in the file system, and then finding out if it is a child of the mount point, and if so (and only then) relativize the path name, is neither natural nor trivial.

**Comment by shoogle** [comment]
It's actually not that difficult to detect if a file is within the AppImage, or rather in the AppDir that is extracted at runtime. Simply take the path to your binary (probably `${MountPoint}/usr/bin`), remove `/usr/bin` from it and see if this matches the beginning of the path to the file (which will probably be in `${MountPoint}/usr/share`). If it matches then the relative path to the file is `../../usr/share` from the binary. If it doesn't match then it's not in the AppImage, so keep the full path. You only have to write one function to do this and you can reuse it as often as you need. Alternatively, you could even use the environment variable `$APPDIR` which stores the mount point and is set at runtime.

**Comment by probonopd** [comment]
GIMP currently also has a need for this https://github.com/probonopd/AppImageKit/issues/83 but could be worked around by GIMP just like it was possible for IrScrutinizer.

**Comment by probonopd** [comment]
Qt Creator seems to suffer from the same problem, at least when installed from `qt-opensource-linux-x64-5.7.0.run`.

The installer hardcodes the path to qmake with is used at startup to determine a Kit ("update Qt version information") into `QMakePath` of `Tools/QtCreator/share/qtcreator/QtProject/qtcreator/qtversion.xml`. By changing this path to a valid one, a Kit is automatically created at startup time.

But changing it to a relative path has unintended consequences:

```
sed -i -e 's|<value type="QString" key="QMakePath">.*</value>|<value type="QString" key="QMakePath">../5.7/gcc_64/bin/qmake</value>|g' Tools/QtCreator/share/qtcreator/QtProject/qtcreator/qtversion.xml
```

Now if `qtcreator` is executed from a directory on the same level as `./5.7/` (`./usr/` in my case), then on startup a Kit is detected and I can create a new project. But running it fails because the relative path put into the config file is not always relative to the original directory but changes, e.g., during compilation.


```
[pid 10809] access("../5.7/gcc_64/bin/qmake", X_OK) = 0
[pid 10809] stat("/home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/../5.7/gcc_64/bin/qmake", 0x7ffdb066d280) = -1 ENOENT (No such file or directory)
[pid 10809] stat("../5.7/gcc_64/bin/qmake", {st_mode=S_IFREG|0755, st_size=2879448, ...}) = 0
[pid 10809] access("../5.7/gcc_64/bin/qmake", X_OK) = 0
[pid 10809] stat("../5.7/gcc_64/bin/qmake", {st_mode=S_IFREG|0755, st_size=2879448, ...}) = 0
[pid 10870] execve("../5.7/gcc_64/bin/qmake", ["../5.7/gcc_64/bin/qmake", "/home/me/untitled3/untitled3.pro", "-r", "-spec", "linux-g++", "CONFIG+=debug", "CONFIG+=qml_debug"], [/* 64 vars */]) = -1 ENOENT (No such file or directory)
```

So the question is: How to define a `QMakePath` in qtversion.xml that is always relative to, e.g., the `qtcreator` executable or its "QTDIR"?

Besides, the installer writes the absolute installation path into
* 5.7/gcc_64/lib/libQt5Core.so.5.7.0
* 5.7/gcc_64/bin/qmake

namely

* qt_hpfxpath
* qt_epfxpath
* qt_prfxpath

and a lot of text files.
Which makes me wonder a) whether that is good practice, because it essentially makes the installed instance of QtCreator un-relocateable; and b) how we should deal with it.

**Comment by probonopd** [comment]
After having talked to one of the Qt Creator developers, it is unlikely that they will change Qt Creator not to use hardcoded paths for the user settings. Hence we will indeed need this as an option.

Can we make it so that if a special build option is passed in like `configure --constant-mountpoint=/tmp/qtcreator_fixed_mountpoint` then `runtime` is built accordingly? It would also be a good idea to have a short warning when such AppImages are launched, 

`This AppImage uses the constant mountpoint /tmp/qtcreator_fixed_mountpoint, this is discouraged"`.

Unfortunately I don't know my way around the required IFDEFs and CMake commands, so PR welcome!

**Comment by probonopd** [comment]
The installer hardcodes the path to qmake with is used at startup to determine a Kit ("update Qt version information") into QMakePath of `Tools/QtCreator/share/qtcreator/QtProject/qtcreator/qtversion.xml`. By changing this path to a valid one, a Kit is automatically created at startup time:

```
sed -i -e 's|<value type="QString" key="QMakePath">.*</value>|<value type="QString" key="QMakePath">../5.7/gcc_64/bin/qmake</value>|g' Tools/QtCreator/share/qtcreator/QtProject/qtcreator/qtversion.xml
```

Now on startup a Kit is detected and I can create a new project. But running it fails because apparently the relative path I used above is not always relative to the original directory but changes, e.g., during compilation.

A Qt Creator deveoper agreed to a patch in QtCreator that will allow die a QMakePath in qtversion.xml that is always relative to, e.g., the qtcreator executable. This means no hardcoded absolute paths will be needed inside the AppImage, which is great. 

However, the same will not be true for settings stored in the user's `$HOME`, hence we still need to build a version of `runtime` with `--constant-mountpoint=/tmp/qtcreator_fixed_mountpoint`.

**Comment by probonopd** [comment]
OpenNX stores a path to "itself" in the configuration file. Why?
Of course this does not work with the ever-changing AppImage mountpoints.

```
me@host:~$ cat .opennx 
[Config]
UserNxDir=/home/me/.nx
CurrentVersion=0.16.729
SystemNxDir=/home/me/OpenNX/OpenNX.AppDir/usr
CupsPath=/usr/sbin/cupsd
NxSshSmartCardSupport=0
```
