### ISSUE TITLE
Provide prebuilt binaries for AppdirAssistant & AppImageAssistant 

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#88]
Previously, you used to provide these both GUI binaries for making app images. But now i couldn't find them on the new website. After going through the git repo, i found that we have to manually compile them which could be a problem for some users. If you can provide **pre compiled binaries** it would be very useful. Thank you.

**EDIT:** Thanks to @RazZziel for directing me to the downlod link. Now, I request to add this link in the appimage.org website too. Also please add 32-bit appimagekit binaries.

**Comment by RazZziel** [comment]
You can find the binaries in the "Releases" section in Github: https://github.com/probonopd/AppImageKit/releases, but:
* They should probably be linked on the website
* They should be named `AppImageAssistant 3.0.0.AppImage` or `AppImageAssistant 3.0.0.run` instead of just `AppImageAssistant`, without version number or extension
* 32bit binaries should be provided (although Travis doesn't seem to support 32bit...)
* AppDirAssistant is missing (it's not even being built by CMake)

**Comment by kskarthik** [comment]
thanks :+1: i didn't notice that

**Comment by probonopd** [comment]
Merged PR to include download link in README.md, thanks @kskarthik
