### ISSUE TITLE
Provide binaries for x86 (32bit) 

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#91]
I just compiled AppImageKit for x86 (32bit) systems. File attached below. Requesting to place them in the releases. Thank you.
* **Compiled on Linux Mint 17.1 [Ubuntu 14.04]** 

[AppImageKit_x86.tar.gz](https://github.com/probonopd/AppImageKit/files/142656/AppImageKit_x86.tar.gz)

**Comment by RazZziel** [comment]
Sorry, missclicked!

**Comment by RazZziel** [comment]
Hmmmm isn't that distro too new to build an app that must run on as many systems as possible? Do the apps run fine on Ubuntu 12.04 or Debian 7, or even Ubuntu 10.04 or Debian 6?

**Comment by kskarthik** [comment]
ubuntu 14.04 is almost 2yrs old right now.

**Comment by RazZziel** [comment]
> ubuntu 14.04 is almost 2 yrs old right now.

Which is still pretty new if we want to run on **all** systems :) There's users out there using Puppy Linux or even Slitaz or Slacko, so we must aim a bit older than what we think most users will be using. I'm still considering Ubuntu 12.04 to be the newest system my apps need to run on, but I'm actually targeting Ubuntu 10.04

> I think most systems run ubuntu.

But not **all** the users; we still need to test on SuSe, Fedora, Archlinux, etc

> Almost all apps run on ubuntu run on debian. However if there is someone who could test this on debian 7 & 6 it would be helpful since i don't have them & no enough bandwidth to download & test those

Yep, testing is a big problem when distributing portable packages :P

**Comment by kskarthik** [comment]
i think this appimagekit is packed with glibc 2

**Comment by probonopd** [comment]
Please submit a pull request that builds the 32-bit version on travis.

**Comment by RazZziel** [comment]
Hm! Until now I assumed that would be impossible because Travis doesn't support 32bit OSs, but that's stupid, a 64bit os should be able to generate 32bit binaries just fine. I'll give it a try.

**Comment by kskarthik** [comment]
Oh! i'm unaware of travis tests :( @RazZziel can u do that ?

**Comment by RazZziel** [comment]
I'm trying, but it's proving tedious: https://travis-ci.org/probonopd/AppImageKit/builds

[Last one](https://travis-ci.org/probonopd/AppImageKit/jobs/111404470) is awesome:
>$ sudo apt-get install -qq --force-yes gcc-multilib g++-multilib libc6-dev-i386 libglib2.0-dev:i386
>You are about to do something potentially harmful.
>To continue type in the phrase 'Yes, do as I say!'
> ?]

**Comment by shoogle** [comment]
I managed to get 32 bit AppImage builds of MuseScore to work on Travis. The main problem I had is that you will end up with a mix of both 32 bit and 64 bit libraries installed on the system, so when it is time to copy them into the AppDir you could end up copying the wrong one. The best solution I found was to build inside a 32 bit chroot (in this case a Docker image) so that you only have access to the 32 bit libraries. My [build script simply pulls either a 32 bit or 64 bit Docker image](https://github.com/musescore/MuseScore/pull/2398/files#diff-aad98a47365a899c0b7d2387934b15f5R32) and then runs the [Recipe](https://github.com/musescore/MuseScore/blob/353f1c1e3191ed6f314940fea92bb53c053c3f0e/build/Linux%2BBSD/portable/Recipe) inside (same recipe works for 32 and 64 bit). Here's the [build log](https://travis-ci.org/musescore/MuseScore/builds/110964068).

MuseScore is GPLv2 but I give you permission to use my contributions from these two AppImage-related pull requests under the MIT license:
https://github.com/musescore/MuseScore/pull/2398
https://github.com/musescore/MuseScore/pull/2362

**Comment by probonopd** [comment]
Did I get it right and the key is 
```
# Build MuseScore AppImage inside 32-bit Docker image
docker run -i -v "${PWD}:/MuseScore" toopher/centos-i386:centos6 /bin/bash -c \
"linux32 --32bit i386 /MuseScore/build/Linux+BSD/portable/Recipe $makefile_overrides"
```

**Comment by shoogle** [comment]
That's right. It does two important things:

1. Pulls a 32 bit Docker image for CentOS that [someone else has been kind enough to make](https://hub.docker.com/r/toopher/centos-i386/). (There are no official 32 bit Docker images.)
2. Runs the command `linux32 --32bit i686` which basically does three things:
   - Restricts to 32 bits
   - Changes the output of `uname -m` from "x86_64" to "i686"
   - Ensures that `yum install` will fetch 32 bit libraries.

Now the chroot is indistinguishable from a 32 bit system.

On 64 bit we simply use the official CentOS image and don't run `linux32`:
<pre>
# Build MuseScore AppImage inside native (64-bit) Docker image
docker run -i -v "${PWD}:/MuseScore" library/centos:6 /bin/bash -c \
"/MuseScore/build/Linux+BSD/portable/Recipe $makefile_overrides"
</pre>

**Comment by probonopd** [comment]
Yes I had been producing 32-bit builds using linux32 and 32-bit chroot environments [before](https://github.com/probonopd/AppImages/blob/master/recipes/subsurface/Recipe) but did not know where to get a 32-bit CentOS docker image.

So @RazZziel @kskarthik pull requests welcome. Ideally so that each recipe gets built for each architecture. If it's worth the hassle...

**Comment by shoogle** [comment]
The only other important (and not obvious) change was to the function I was using to [locate libraries](https://github.com/musescore/MuseScore/pull/2398/files#diff-648855eea2924892f388f6690d940de6L130) when I needed to copy them into the AppDir.

Before I was doing:
<pre>
locateLib() {
echo "$(ldconfig -p | grep "$1" | awk '{print $4}')"
}
</pre>
That works about 99% of the time, but sometimes `awk` would return the wrong thing (i.e. not a path) and sometimes multiple results would be returned. I found this is more reliable:
<pre>
locateLib() {
echo "$(ldconfig -p | awk '{print $4}' | grep "$1" | head -n1)"
}
</pre>
(Notice that `awk` is now done before `grep` and I use `head` to keep only the first result.)

I think you do something similar in some of your recipes so you might want to change it.

**Comment by RazZziel** [comment]
That's awesome @shoogle, thanks! I'll give it a try

Provided our build scripts are currently focused on Ubuntu/Debian, I'll probably try to use an old enough 32bit [Ubuntu](https://hub.docker.com/r/32bit/ubuntu/) or [Debian](https://hub.docker.com/r/32bit/debian/) docker image. I'm not sure whether we should use two docker containers like you, or if we can build 32bit on the container and 64bit in the host.

**Comment by probonopd** [comment]
Well @RazZziel for significant apps like Scribus, Subsurface, and others we do use CentOS 6 and I would highly recommend it for recipes where we are building from source. It really helps increase compatibility with not-too-recent systems, while still providing reasonably new compilers and stuff. So Thanks @shoogle very much for your ideas. Would love to see more 32-bit (and ARM!) AppImages.

**Comment by shoogle** [comment]
You're welcome, guys! Thanks for AppImageKit!

@RazZziel, just thought I'd add that  it is actually less work to build both 32 bit and 64 bit inside containers because the same recipe will work in both without modification (all 32 bit dependencies have the same names as 64 bit counterparts), but it wouldn't work outside the container without modification since Ubuntu (i.e. Travis) dependencies are named differently to CentOS dependencies.

**Comment by RazZziel** [comment]
> but it wouldn't work outside the container without modification since Ubuntu (i.e. Travis) dependencies are named differently to CentOS dependencies.

I meant to build 64bit outside the container, and 32bit inside a Debian/Ubuntu container, rather than a CentOS container, just to maintain dependencies. However if

> but it wouldn't work outside the container without modification since Ubuntu (i.e. Travis) dependencies are named differently to CentOS dependencies.

In that case it does make sense to use CentOS.

Regarding ARM, I had been [looking into that](https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html) some time ago; it involved setting up a qemu VM, but it's doable

**Comment by RazZziel** [comment]
Looks like it's working!
* 32bit: https://travis-ci.org/probonopd/AppImageKit/jobs/113335852#L672-L675
* 64bit: https://travis-ci.org/probonopd/AppImageKit/jobs/113335853#L663-L666

Regarding ARM, I'll be trying several docker images that actually integrate the quemu chroot inside (see https://travis-ci.org/probonopd/AppImageKit/builds/113582095)

Does anyone know how I can download the artifacts generated without a release in Github, to test if they actually work?

**Comment by shoogle** [comment]
Nice job! If you want to test them you'll need to upload them somewhere from within Travis. You could upload to a test repo on Bintray, but this involves a bit of work. However, if @probonopd wants Bintray uploads then it is work that would have to be done anyway.

*IF* you were building in your own fork of AppImageKit you *could* do it like this:

1. Create an account for yourself on [Bintray.com](https://bintray.com/) (free, and you can link with your GitHub account) and create a "generic" repository (i.e. not a DEB or RPM repo) on Bintray.
2. Create an account on  [Travis-CI.org](https://travis-ci.org/) (again, free and you can link to GitHub) and enable Travis builds for your fork of AppImageKit.
3. Copy [bintray.sh](https://github.com/shoogle/AppImages/blob/master/bintray.sh) from [probonpd/AppImages](https://github.com/probonopd/AppImages).
4. Set [these variables](https://github.com/probonopd/AppImages/blob/master/bintray.sh#L13-L20) inside bintray.sh *(except set the Bintray API key as an [environment variable in Travis settings](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings) so that it remains secret)*.
5. Add [dependencies for bintray.sh](https://github.com/probonopd/AppImages/blob/master/.travis.yml#L5-L7) to .travis.yml.
6. In your recipe [give read+write access to the AppImage and all parent directories in its path](https://github.com/musescore/MuseScore/pull/2362/files#diff-caca19de8968478b1259527451d6ac1cR117).
7. Run bintray.sh just after the AppImage is created, from *outside* the Docker container, like [this](https://github.com/probonopd/AppImages/blob/master/.travis.yml#L22-L23).

*However*, since you are not on your own fork, rather you are committing straight into @probonopd's original git repo, you can't set the Bintray API key as an environment variable in step 4 (unless you know his password for Travis), so you'll either have to hard code the API key into the file and revoke it later (in which case skip step 2 since you'd be using @probonopd's Travis account), or create a fork of AppImageKit for yourself now.

**Comment by kskarthik** [comment]
@probonopd so, I think things are fixed. Close this issue now ?

**Comment by shoogle** [comment]
Not just yet, I think. AppImages are being built, but they haven't been tested yet, nor have they been made available for users to download.

**Comment by probonopd** [comment]
Very cool @RazZziel

**Comment by RazZziel** [comment]
I'm sorry for the delay, time is scarce
**Huge** thanks for the detailed tips @shoogle 
I went the easy way, created [a Bintray repo](https://bintray.com/raziel/generic), and encrypted the API key in @probonopd's .travis.yml. For now, instead of bintray.sh I'll be using [Travis implementation](https://docs.travis-ci.com/user/deployment/bintray).

**Comment by shoogle** [comment]
@RazZziel, I can't see any builds in your Bintray repo, perhaps they are there but unpublished? It would be good to be able to test the ARM builds to make sure they really did get cross-compiled and haven't just been built for the host architecture. The [build times](https://travis-ci.org/probonopd/AppImageKit/builds/114448711) seem a bit suspicious (64 bit took longer than 32 bit and even one of the ARM builds!) so it would be good to make sure.

**Comment by RazZziel** [comment]
@shoogle 
>  I can't see any builds in your Bintray repo, perhaps they are there but unpublished?

Deployment didn't work, because my branch doesn't have deployment permission. I'll either use your script or fork the project and try again.

> It would be good to be able to test the ARM builds to make sure they really did get cross-compiled and haven't just been built for the host architecture

Actually that's exactly what happened, I ran a `file` command on the resulting binaries, and they're all x86_64 :( I guess the ARM containers just pack cross-compilers that we need to use explicitly, rather than enclosing a transparent ARM qemu machine.

**Comment by shoogle** [comment]
That's a pity. You probably just have to enable the cross compiler to get it to work though, something like this in .travis.yml might allow you to get a bit further:
<pre>
docker run -i -v "${PWD}:/AppImage" "$DOCKER_IMAGE" /bin/bash -c "PATH=\"/path/to/crosscompiler:\$PATH\"  /AppImage/build.sh"
</pre>

You might still run into problems later though when it is time to add libraries to the AppImage. The ideal way is to enter an [ARM chroot using QEMU](https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html) like you said. There are some actual ARM docker images if you search for "arm" or "rpi" on [Docker Hub]( https://hub.docker.com), but I don't know if it's possible to get them to work with QEMU.

**Comment by RazZziel** [comment]
I just realized this makes very little sense, all the packaging work is already done in https://github.com/probonopd/AppImages/tree/master/recipes/appimageassistant.

Where is AppImageAssistant & co. going to be built? [AppImageKit](https://github.com/probonopd/AppImageKit)? [AppImages](https://github.com/probonopd/AppImages)? Both? If it's [AppImageKit](https://github.com/probonopd/AppImageKit), it makes sense to adapt the build process to upload to BinTray (generate comment, version, etc), but otherwise you can just generate the proper Dockerfiles in [AppImages](https://github.com/probonopd/AppImages).

**Comment by shoogle** [comment]
@probonopd's decision, but my vote would be to build here. Building here is automatic on every commit whereas building in the AppImages repo has to be triggered manually. Plus it increases exposure of the whole Bintray process; it was a while before I was aware of the existence of the AppImages repo.

Dockerfiles are there to create custom Docker images that have all the dependencies preinstalled, but AppImageKit is small and has few dependencies so it doesn't really need a Dockerfile.

**Comment by probonopd** [comment]
Just from a practical perspective, I had started to do all the Docker handling, AppImage building and Bintray uploading over in the AppImages repo, because these things are not essential to AppImageKit but merely one way (out of many) of how to create and distribute AppImages. And since at some point I had the Docker handling, AppImage building and Bintray uploading working well in that repo I started using it to "eat our own dogfood" and use the same for e.g., AppImageUpdate, too. 

But @shoogle has a good point, building AppImageKit core components such as AppRun and runtime.c doesn't need custom dockerfiles so we could keep doing that in this repo.

**Comment by RazZziel** [comment]
https://bintray.com/raziel/generic/AppImageAssistant/view: is Bintray dead, or are my packages killing it? :|

**Comment by probonopd** [comment]
@RazZziel I do see your AppImages on Bintray, here: https://bintray.com/raziel/generic/AppImageAssistant/view#files but I don't have a 32-bit system at hand in this very moment to try them out.

**Comment by RazZziel** [comment]
Yep, the page was broken before, I filed a bug report and looks like they've just fixed it

**Comment by RazZziel** [comment]
Ok, integration should be complete, it's [building fine](https://travis-ci.org/probonopd/AppImageKit/builds/115256818), [uploading fine](https://bintray.com/raziel/generic), and the 32bit builds are running fine on my machine. Please test on your machines.

I'll create the PR as-is, @probonopd feel free to change the bintray credentials to the final ones.

I made [some tweaks in bintray.sh](https://github.com/probonopd/AppImageKit/commit/11896b1e2bd2dabd7462603cc8844a591ce6b6b4) that may be useful for the AppImages repo.

**Comment by RazZziel** [comment]
Btw, I stopped using `git rev-list --count HEAD` for versioning, because it will give either wrong or empty results in docker, so now I'm using only `git describe --tags`, which should provide a good enough output both for releases (0 commits after a tag) and for nightlies (>0 commits after a tag)

**Comment by shoogle** [comment]
If you need to use `git` commands you could always do so in the native Travis environment before entering the Docker chroot. Either save the output in a file and read it inside the chroot, or store it in a variable and pass it into the chroot. But if you're happy with the new naming scheme then there's no need to change it.

**Comment by RazZziel** [comment]
Oops, I meant Travis, not Docker

Travis by default fetches the last 50 commits (`--depth=50`), not the whole history, which seems to alter the output of `git rev-list --count HEAD`

**Comment by shoogle** [comment]
I see. For MuseScore we version nightlies with \<date>-\<branch>-\<commit>. E.g.:
<pre>
MuseScoreNightly-201602261142-2.0.3-3c636ec-i686.AppImage
</pre>
Of course, the filename is quite long, but maybe just the date would do for you.

**Comment by RazZziel** [comment]
Hmm, I like the date/time idea, we can add that

The filename being too long is not really a problem (specially for nightlies), and having the exact commit is really useful to associate binaries to source code, handy for bug reports etc

**Comment by probonopd** [comment]
Please do a PR regarding bintray.sh in the [AppImages](https://github.com/probonopd/AppImages) repo; I'd like to maintain it in just 1 place.

**Comment by RazZziel** [comment]
This was done in https://github.com/probonopd/AppImageKit/pull/112

**Comment by probonopd** [comment]
To everyone reading this, if you are interested in ARM builds, check out Open Build Service which can build AppImages for 32-bit and 64-bit Intel and ARM architectures. Instructions: https://github.com/probonopd/AppImageKit/wiki/Using-Open-Build-Service
